---
version: '3'
services:
  zookeeper:
    networks:
      - library-api
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    networks:
      - library-api
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # Postgresql
  postgres:
    networks:
      - library-api
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  # Keycloak
  keycloak:
    networks:
      - library-api
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./realms:/opt/keycloak/data/import
    ports:
      - "8181:8080"
    command:
      - start-dev
      - --import-realm

  #  Discovery-server
  discovery-server:
    container_name: discovery-server
    image: discovery-server
    ports:
      - "8761:8761"
    networks:
      - library-api

  # TODO: fix api-gateway
  #  Api-gateway
  api-gateway:
    image: api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - library-api
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET=kkOpxkh4kEmb0remraSYVGYHxHEu22Er
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://keycloak:8181/realms/library-api-realm
    depends_on:
      - discovery-server

  # Book-service
  book-service:
    image: book-service
    container_name: book-service
    ports:
      - "6060:6060"
    networks:
      - library-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/library
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka
    depends_on:
      - postgres
      - broker
      - discovery-server

  # Library-service
  library-service:
    networks:
      - library-api
    image: library-service
    container_name: library-service
    ports:
      - "7070:7070"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/library
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka
    depends_on:
      - postgres
      - broker
      - discovery-server

networks:
  library-api:
    driver: bridge